In [1]:
import descwl
import numpy as np
import os
import fitsio

In [27]:
band = "u"
survey_name = "LSST"
pars = descwl.survey.Survey.get_defaults(
    survey_name=survey_name,
    filter_band=band,
)
pars["survey_name"] = survey_name
pars["filter_band"] = band

pars['image_width'] = 10
pars['image_height'] = 10
svy = descwl.survey.Survey(**pars)

calib_mag_zero = 30.0
s_zp = svy.zero_point
s_et = svy.exposure_time
(10.0**(0.4*(calib_mag_zero - 24.0))/s_zp/s_et * np.sqrt(svy.mean_sky_level)) ** 2.0

0.4517053516191986

In [69]:
indir1 = "/gpfs02/work/xiangchong.li/work/hsc_data/s23b/deepCoadd_anacal_v2/fields/"
dd = fitsio.read(
    os.path.join(
        indir1,
        "hectomap.fits",
    )
)
dd2 = fitsio.read(
    os.path.join(
        indir1,
        "hectomap_response.fits",
    )
)

In [70]:
de1_dg1 = dd2["R"] - np.sqrt(3.0) * dd2["e44c"] + np.sqrt(2.0) * dd2["e22c"] * dd["e1"]
de2_dg2 = dd2["R"] + np.sqrt(3.0) * dd2["e44c"] + np.sqrt(2.0) * dd2["e22s"] * dd["e2"]
de1_dg2 = -np.sqrt(3.0) * dd2["e44s"] + np.sqrt(2.0) * dd2["e22s"] * dd["e1"]
de2_dg1 = -np.sqrt(3.0) * dd2["e44s"] + np.sqrt(2.0) * dd2["e22c"] * dd["e2"]

In [71]:
np.max(np.abs(de1_dg1 - dd["de1_dg1"]))

0.0036216970697820483

In [72]:
np.max(np.abs(de2_dg2 - dd["de2_dg2"]))

0.002188837357199172

In [73]:
de1_dg2

array([ 0.07480686,  0.14143206, -0.158994  , ...,  0.15386596,
        0.05746969,  0.01612409])

In [74]:
dd["de1_dg2"]

array([ 0.07473594,  0.14152135, -0.15868137, ...,  0.15399813,
        0.05612375,  0.01700573])

In [75]:
de2_dg1

array([ 0.08660373,  0.12491787, -0.16036451, ...,  0.16406011,
        0.06586196, -0.10891393])

In [76]:
dd["de2_dg1"]

array([ 0.08656997,  0.12511557, -0.1600489 , ...,  0.16409509,
        0.06445428, -0.10669491])

In [77]:
fname = "/gpfs02/work/xiangchong.li/work/hsc_data/catalog_v2/s23b_shape/anacal_hectomap.fits"
a = fitsio.read(fname)
fname = "/gpfs02/work/xiangchong.li/work/hsc_data/catalog_v2/s23b_shape/.response/hectomap.fits"
b = fitsio.read(fname)

In [78]:
de1_dg1 = b["response"] - np.sqrt(3.0) * a["e44c"] + np.sqrt(2.0) * a["e22c"] * a["e1"]
de2_dg2 = b["response"] + np.sqrt(3.0) * a["e44c"] + np.sqrt(2.0) * a["e22s"] * a["e2"]
de1_dg2 = -np.sqrt(3.0) * a["e44s"] + np.sqrt(2.0) * a["e22s"] * a["e1"]
de2_dg1 = -np.sqrt(3.0) * a["e44s"] + np.sqrt(2.0) * a["e22c"] * a["e2"]

In [87]:
print(np.average(np.abs(de1_dg1 - dd["de1_dg1"])))
print(np.average(np.abs(de2_dg1 - dd["de2_dg1"])))
print(np.average(np.abs(de2_dg2 - dd["de2_dg2"])))
print(np.average(np.abs(de1_dg2 - dd["de1_dg2"])))

8.012273142949198e-07
0.0014742407255299902
1.116728150547804e-06
0.0014780952780255542


array([ 0.08656997,  0.12511557, -0.1600489 , ...,  0.16409509,
        0.06445428, -0.10669491])

In [80]:
np.sum(np.abs(a["e44c"] - dd2["e44c"]))

0.0

In [81]:
np.min(a["e44c"])

-2.0754237152754884

In [82]:
np.max(dd2["e44c"])

6.626827390496669

In [62]:
np.sum(np.abs(a["e22s"] - dd2["e22s"]))

0.0

In [38]:
np.sum(np.abs(a["e1"] - dd["e1"]))

0.0

In [39]:
b["response"]

array([0.49689701, 0.25486802, 0.05312357, ..., 0.23442425, 0.21740096,
       0.40605128])

In [40]:
dd2["R"]

array([0.49689701, 0.25486802, 0.05312357, ..., 0.23442425, 0.21740096,
       0.40605128])

In [41]:
de1_dg1 

array([ 0.57846969,  0.38218158, -0.10787137, ...,  0.39630544,
        0.27480441,  0.40383051])

In [42]:
dd["de1_dg1"]

array([0.49856811, 0.24431284, 0.1425271 , ..., 0.25832556, 0.29169801,
       0.82789942])

In [49]:
a["e44s"]

array([-0.03357587, -0.07271796,  0.09247402, ..., -0.08925673,
       -0.03349011, -0.00471635])

In [50]:
dd2["e44s"]

array([-0.03357587, -0.07271796,  0.09247402, ..., -0.08925673,
       -0.03349011, -0.00471635])

In [91]:
catalog = fitsio.read("/gpfs02/work/xiangchong.li/work/hsc_data/catalog_v2/s23b_shape/anacal_hectomap.fits")
response = fitsio.read("/gpfs02/work/xiangchong.li/work/hsc_data/catalog_v2/s23b_response/xiangchong-3blind/hectomap_0.fits")
sim = fitsio.read("/gpfs02/work/xiangchong.li/work/hsc_data/catalog_v2/mock_test/gpx2023s001_hectomap_rotmat0_shear_catalog.fits")

In [90]:
# Check the object_ids are the same
np.testing.assert_array_equal(catalog["object_id"], mock["object_id"])
np.testing.assert_array_equal(catalog["object_id"], response["object_id"])

In [122]:
dm1_plus1 = 1.026881
do_rotation = False

import numpy as np
def _rotate(*, c, s, phi_rad):
    # Do rotation
    cp = np.cos(phi_rad)
    sp = np.sin(phi_rad)
    return c * cp - s * sp, c * sp + s * cp

def get_response_average(*, catalog, response, dm1_plus1=1.0, sel_response=0.0):
    response_average = np.average(catalog["wsel"] * (
        response["response"] * dm1_plus1 
        + np.sqrt(2.0) / 2.0 * (
            catalog["e22c"] * catalog["e1"]
            + catalog["e22s"] * catalog["e2"]
        )
    )) + sel_response
    return response_average

def get_shear(catalog, response, sim=None, dm1_plus1=1.0, do_rotation=True, sel_response=0.0):
    """
    Compute per-object shear estimators (g1, g2) from measured spin moments and a
    (scalar) shear response, optionally applying a known rotation and optionally
    including first-order simulated shear terms.

    Parameters
    ----------
    catalog : mapping or numpy structured array
        Per-object measurements. Must provide fields/keys:
        - "wsel" : selection and detection weight (float array)
        - "e1", "e2" : spin-2 ellipticity-like components (float arrays)
        - "e22c", "e22s" : spin-2 components used in the response correction (float arrays)
        - "e44c", "e44s" : spin-4 components used in the response correction (float arrays)

    response : mapping
        Response information. Must provide:
        - "response" : base (scalar or per-object) shear response term.

    sim : mapping or None, optional
        If provided, enables two behaviors:
        - rotation: uses `sim["rot_angle"]` (radians) when `do_rotation=True`
        - injected shear correction: uses `sim["g1_sim"]` and `sim["g2_sim"]`
          to include first-order terms in the numerator (and optional selection
          response terms via `sel_response`).
        If None, the estimator is computed without injected-shear corrections.

    dm1_plus1 : float, optional
        Multiplicative blinding factor applied to `response["response"]`.
        Use 1.0 for no extra scaling.

    do_rotation : bool, optional
        If True and `sim` is not None, rotate all spin components by
        `rot_angle` (spin-2 uses 2*rot_angle; spin-4 uses 4*rot_angle).
        If False (or `sim` is None), no rotation is applied.

    sel_response : float, optional
        Additional selection/detection response contribution. In the current
        implementation it is added to the response denominator and, when `sim`
        is provided, contributes to the numerator as `g*_sim * sel_response`.

    Returns
    -------
    g1 : numpy.ndarray
        Per-object shear estimator for the first component.

    g2 : numpy.ndarray
        Per-object shear estimator for the second component.
    """
    if do_rotation and (sim is not None):
        rot_angle = sim["rot_angle"]
    else:
        rot_angle = 0.0
    # rotation
    e1, e2 = _rotate(c=catalog["e1"], s=catalog["e2"], phi_rad=2.0*rot_angle)
    e22c, e22s = _rotate(c=catalog["e22c"], s=catalog["e22s"], phi_rad=2.0*rot_angle)
    e44c, e44s = _rotate(c=catalog["e44c"], s=catalog["e44s"], phi_rad=4.0*rot_angle)
    # shear
    de1_dg1 = (
        response["response"] * dm1_plus1 
        - np.sqrt(3.0) * e44c + np.sqrt(2.0) * e22c * e1 
    )
    de2_dg2 = (
        response["response"] * dm1_plus1 
        + np.sqrt(3.0) * e44c + np.sqrt(2.0) * e22s * e2 
    )
    de1_dg2 = -np.sqrt(3.0) * e44s + np.sqrt(2.0) * e22s * e1
    de2_dg1 = -np.sqrt(3.0) * e44s + np.sqrt(2.0) * e22c * e2
    # include detection and selection response
    if sim is None:
        we1 = catalog["wsel"] * e1
        we2 = catalog["wsel"] * e2
    else:
        we1 = catalog["wsel"] * (e1 + de1_dg1 * sim["g1_sim"] + de1_dg2 * sim["g2_sim"]) + sim["g1_sim"] * sel_response
        we2 = catalog["wsel"] * (e2 + de2_dg1 * sim["g1_sim"] + de2_dg2 * sim["g2_sim"]) + sim["g2_sim"] * sel_response
    response_average = get_response_average(
        catalog=catalog, response=response, 
        dm1_plus1=dm1_plus1, sel_response=sel_response,
    )
    g1 = we1 / response_average
    g2 = we2 / response_average
    return g1, g2

In [128]:
response_average = np.average(dd["wsel"] * (dd["de1_dg1"] + dd["de2_dg2"]) / 2.0)
print(response_average)
g1 = dd["e1"] * dd["wsel"] / response_average
g2 = dd["e2"] * dd["wsel"] / response_average

0.26353286736130543


In [129]:
g1

array([ 0.61440726, -0.56959737,  0.07864631, ...,  0.08341285,
       -0.02365462,  0.096001  ])

In [130]:
g2

array([0.74640687, 0.43203206, 0.01856567, ..., 0.1083648 , 0.30809552,
       1.08184484])

In [132]:
get_shear(catalog=catalog, response=response, dm1_plus1=dm1_plus1)

0.2635330397817549


(array([ 0.61440686, -0.569597  ,  0.07864625, ...,  0.0834128 ,
        -0.02365461,  0.09600094]),
 array([0.74640638, 0.43203178, 0.01856565, ..., 0.10836473, 0.30809532,
        1.08184414]))